= Git in Software Development

This repository holds the sample application for illustrating Git in Software Development.

// TODO: Add presentation ro repository and link it here

== Description

This repository provides a sample application which is build in Jenkins to illustrate the relation of Git Branches, Versions and CI/CD. 

== Technologies

* link:https://git-scm.com/[Git 2.21.0.windows.1]
* link:https://docs.docker.com/[Docker 19.03.8]
* link:https://docs.docker.com/compose/[Docker Compose 1.25.4]

== Resources

== Prerequisites

You need to expose the Docker Daemon via tcp (unprotected). +  
The following environment variables needs to be defined for docker-compose. The simplest way to provide them is to create a ``.env`` file in the ``./docker`` directory. 

* ``DOCKER_HOST_URI`` +
  The Docker Host URI in the form of ``tcp://<HOST>:<PORT>``
* ``RUN_AS`` +
  Defines with which use the jenkins container shall run. Either ``root`` or ``jenkins``
* ``JENKINS_PORT`` +
  The port jenkins is running on 
* ``JENKINS_ADMIN_PASSWORD``` +
  The password of the admin user
* ``GITHUB_USERNAME`` +
  Your github username
* ``GITHUB_ACCESS_TOKEN`` +
  Your github personal access token
* ``JNLP_JENKIS_URL`` +
  The Jenkins URL used by the jnlp docker agent

IMPORTANT: With Docker for Windows set the environment varibales to: + 
``DOCKER_HOST_URI=tcp://host.docker.internal:2375`` +
``RUN_AS=root`` +
``JNLP_JENKIS_URL=http://host.docker.internal:50000`` +
With a native Linux host set the environment varibales to: + 
``DOCKER_HOST_URI=tcp://<DOCKER0_IP>:2375`` +
``RUN_AS=jenkins`` +
``JNLP_JENKIS_URL=http://<DOCKER0_IP>:50000`` + 
See link:https://stackoverflow.com/questions/31324981/how-to-access-host-port-from-docker-container[here] why

== Setup

. Go to ``./docker/``
. Execute ``docker-compose build``
. Execute ``docker-compose up``
. Go to ```http://localhost:${JENKINS_PORT}``
. Login with ``admin:${JENKINS_ADMIN_PASSWORD}``