apiVersion: apps/v1
kind: Deployment
metadata:
  name: "${NAME}"
  labels:
    app: "${NAME}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "${NAME}"
  template:
    metadata:
      labels:
        app: "${NAME}"
    spec:
      containers:
        - name: app
          image: "${IMAGE_TAG}"
          ports:
            - containerPort: 8080
          env:
            - name: GIT_BRANCH
              value: ${GIT_BRANCH}
            - name: GIT_COMMIT
              value: ${GIT_COMMIT}
            - name: VERSION
              value: ${VERSION}
            - name: BUILD_TIMESTAMP
              value: ${BUILD_TIMESTAMP}