version: '3.3'
services:
    jenkins:    
        build:
            context: ./jenkins
            args:
                VERSION: "2.235-slim"        
                # WINDOWS ONLY, we need to run root otherwise we cannot access 'host.docker.internal'
                RUN_AS: "root"
                ARG KUBECTL_VERSIO: "1.16.5-00"
                DOCKER_CE_CLI_VERSION: "5:19.03.8~3-0~debian-buster"
        ports:
            # The jenkins web app
            - "${JENKINS_PORT}:8080"
            # The jenkins jnlp agent listener
            - "50000:50000"
        environment:
            - "TZ=Europe/Vienna"
            # Plugin download could fail because of timeouts, so increase it
            - "CURL_CONNECTION_TIMEOUT=60"
            # JAV_OPTS for Jenkins
            - "JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Djava.util.logging.config.file=/usr/share/jenkins/ref/logging.properties"
            # Used by jenkins CASC and docker-compose.yml
            - "DOCKER_HOST=${DOCKER_HOST_URI}"
            - "JNLP_JENKIS_URL=${JNLP_JENKIS_URL}"
            - "JNLP_NEXUS_URL=${JNLP_NEXUS_URL}"
            - "RUN_AS=${RUN_AS}"
            - "GITHUB_USERNAME=${GITHUB_USERNAME}"
            - "NEXUS_USERNAME=${NEXUS_USERNAME}"
            - "DOCKER_HUB_USERNAME=${DOCKER_HUB_USERNAME}"
            - "DOCKER_HUB_REGISTRY_REPOSITORY=${DOCKER_HUB_REGISTRY_REPOSITORY}"
            - "KUBERNETES_URL=${KUBERNETES_URL}"
            - "JENKINS_AGENT_IMAGE_TAG=${JENKINS_AGENT_IMAGE_TAG}"
        volumes:
            # The docker volume for persistence
            - jenkins-data:/var/jenkins_home
            # Map the config files in the container
            - ../jenkins-config/casc:/usr/share/jenkins/ref/config
            # Map logging configuration in container
            - ../jenkins-config/logging.properties:/usr/share/jenkins/ref/logging.properties:ro
        privileged: true
        # Inject defined and used secrets
        secrets:
            - nexusPassword
            - jenkinsAdminPassword
            - dockerHubPassword
            - githubAccessToken
            - kubeConfig
        # The healthcheck for jenkins
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080"]
            interval: 5s
            timeout: 5s
            retries: 5
    nexus:
        image: "sonatype/nexus3:3.23.0"
        ports:
            - "${NEXUS_PORT}:8081"
        environment:
            - "INSTALL4J_ADD_VM_PARAMS=-Xms2g -Xmx2g -XX:MaxDirectMemorySize=2g"
        volumes:
            - "nexus-data:/nexus-data"
        # The healthcheck for nexus
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8081"]
            interval: 5s
            timeout: 5s
            retries: 5
secrets:
    nexusPassword:
        file: secrets/nexusPassword.txt
    jenkinsAdminPassword:
        file: secrets/jenkinsAdminPassword.txt
    dockerHubPassword:
        file: secrets/dockerHubPassword.txt
    githubAccessToken:
        file: secrets/githubAccessToken.txt
    kubeConfig:
        file: secrets/kubeConfig.txt
volumes:
    jenkins-data:
    nexus-data: