#!groovy

pipeline {
    agent {
        node {
            label 'docker-agent'
        }
    }

    tools {
        jdk 'openjdk-11'
        maven 'maven-3.6.3'
    }

    environment {
        REVISION = buildRevisionForBranch("app/")
    }

    options {
        disableConcurrentBuilds()
        parallelsAlwaysFailFast()
    }

    stages {
        stage("Prepare") {
            steps {
                script {
                    sh "mkdir -p ${WORKSPACE}/build-result"
                    echo "Revision: ${REVISION}"
                }
            }
        }

        stage("Build Artifact") {
            steps {
                script {
                    dir('app') {
                        configFileProvider([configFile(fileId: 'maven-settings', variable: 'MAVEN_SETTINGS')]) {
                            sh "mvn -s ${MAVEN_SETTINGS} -B clean install deploy -Drevision=${REVISION}"
                        }
                    }
                }
            }
        }
    }
}

static def replaceCharacterForRevision(String branch = "") {
    return branch.replace("/", "-")
            .replace("_", "-")
}

def buildRevisionForBranch(String pomLocation = "./") {
    def SNAPSHOT_SUFFIX = "-SNAPSHOT"
    def branch = "${env.GIT_BRANCH}".trim().toLowerCase()
    if ("develop" == branch) {
        pom = readMavenPom file: pomLocation + 'pom.xml'
        return pom.properties['revision'] + SNAPSHOT_SUFFIX
    } else if (branch.startsWith("feature/")) {
        return replaceCharacterForRevision(branch).toUpperCase() + SNAPSHOT_SUFFIX
    } else if (branch.startsWith("PR-")) {
        return replaceCharacterForRevision(branch).toUpperCase() + SNAPSHOT_SUFFIX
    } else if (branch.startsWith("release/") || branch.startsWith("hotfix/")) {
        pom = readMavenPom file: pomLocation + 'pom.xml'
        return pom.properties['revision'] + "-RC${BUILD_NUMBER}"
    } else {
        error("Branch not detected. branch=${branch}")
    }
}