#!groovy

pipeline {
    agent any

    environment {
        REVISION = buildRevisionForBranch("app/")
    }

    options {
        disableConcurrentBuilds()
        parallelsAlwaysFailFast()
    }

    stages {
        stage("Prepare") {
            steps {
                script {
                    sh "mkdir -p ${WORKSPACE}/build-result"
                    echo "Revision: ${REVISION}"
                }
            }
        }

        stage("Build Artifact") {
            agent {
                node {
                    label 'docker-agent'
                }
            }
            steps {
                script {
                    dir('app') {
                       sh 'ls -lrta'
                    }
                }
            }
        }
    }

    post {
        always {
            sh "rm -rf ${WORKSPACE}/build-result"
        }
    }
}

def replaceCharacterForRevision(String branch = "") {
    return branch.replace("/", "-")
                 .replace("_", "-")
}

def buildRevisionForBranch(String pomLocation = "./") {
    def SNAPSHOT_SUFFIX = "-SNAPSHOT"
    def branch = "${env.GIT_BRANCH}".trim().toLowerCase()
    if ("develop" == branch) {
        pom = readMavenPom file: pomLocation + 'pom.xml'
        return pom.properties['revision'] + SNAPSHOT_SUFFIX
    } else if (branch.startsWith("feature/")) {
        return replaceCharacterForRevision(branch).toUpperCase() + SNAPSHOT_SUFFIX
    } else if (branch.startsWith("PR-")) {
        return replaceCharacterForRevision(branch).toUpperCase() + SNAPSHOT_SUFFIX
    } else if (branch.startsWith("release/") || branch.startsWith("hotfix/")) {
        pom = readMavenPom file: pomLocation + 'pom.xml'
        return pom.properties['revision'] + "-RC${BUILD_NUMBER}"
    } else {
        error("Branch not detected. branch=${branch}")
    }
}